# Generated by Django 5.0.6 on 2026-09-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='catalog.sucursal')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_auth.usuario')),
                ('id_variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='catalog.productovariante')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventory_movement',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('stock_maximo', models.IntegerField(default=100)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='catalog.sucursal')),
                ('id_variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='catalog.productovariante')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock_item',
                'unique_together': {('id_sucursal', 'id_variante')},
            },
        ),
    ]
