# Generated by Django 5.0.6 on 2026-09-12 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fittingreservation',
            name='id_variante',
        ),
        migrations.CreateModel(
            name='FittingReservationItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.fittingreservation')),
                ('id_variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='catalog.productovariante')),
            ],
            options={
                'verbose_name': 'Prenda de Reserva',
                'verbose_name_plural': 'Prendas de Reserva',
                'db_table': 'fitting_reservation_item',
            },
        ),
    ]
