# Generated by Django 5.0.6 on 2026-09-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_fittingreservation_id_variante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingreservationitem',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPRADO', 'Comprado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=20),
        ),
    ]
