# Generated by Django 5.0.6 on 2026-09-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTryOnSession',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_cliente', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fecha_sesion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='users_auth.cliente')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='catalog.producto')),
            ],
            options={
                'verbose_name': 'Sesión AR',
                'verbose_name_plural': 'Sesiones AR',
                'db_table': 'ar_tryon_session',
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id_conversacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_bot', models.TextField()),
                ('fecha_mensaje', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='users_auth.cliente')),
            ],
            options={
                'verbose_name': 'Conversación Chatbot',
                'verbose_name_plural': 'Conversaciones Chatbot',
                'db_table': 'chatbot_conversation',
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('productos_recomendados', models.JSONField()),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='users_auth.cliente')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'db_table': 'recommendation_log',
            },
        ),
    ]
