# backend/apps/innovation/migrations/0002_asegurar_tablas_ia.py
#
# NUEVO (CU17/CU18/CU19): asegura que existan las tablas de IA.
#
# En Neon la migración 0001 figuraba como aplicada, pero las tablas
# ar_tryon_session, chatbot_conversation y recommendation_log no existían
# (los endpoints que las usan respondían 500). Esta migración las crea solo si
# faltan: con "IF NOT EXISTS" no toca nada donde ya existen (por ejemplo, la
# base local) y no cambia el estado de los modelos de Django.
from django.db import migrations

SENTENCIAS = [
    """
    CREATE TABLE IF NOT EXISTS "ar_tryon_session" (
        "id_sesion" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "imagen_cliente" text NULL,
        "resultado" text NULL,
        "fecha_sesion" timestamp with time zone NOT NULL,
        "id_cliente" integer NOT NULL
            REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY DEFERRED,
        "id_producto" integer NOT NULL
            REFERENCES "producto" ("id_producto") DEFERRABLE INITIALLY DEFERRED
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS "ar_tryon_session_id_cliente_37d8b567"
        ON "ar_tryon_session" ("id_cliente")
    """,
    """
    CREATE INDEX IF NOT EXISTS "ar_tryon_session_id_producto_0cad1fcd"
        ON "ar_tryon_session" ("id_producto")
    """,
    """
    CREATE TABLE IF NOT EXISTS "chatbot_conversation" (
        "id_conversacion" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "mensaje_usuario" text NOT NULL,
        "respuesta_bot" text NOT NULL,
        "fecha_mensaje" timestamp with time zone NOT NULL,
        "id_cliente" integer NOT NULL
            REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY DEFERRED
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS "chatbot_conversation_id_cliente_3ff03da9"
        ON "chatbot_conversation" ("id_cliente")
    """,
    """
    CREATE TABLE IF NOT EXISTS "recommendation_log" (
        "id_recomendacion" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "productos_recomendados" jsonb NOT NULL,
        "fecha_recomendacion" timestamp with time zone NOT NULL,
        "id_cliente" integer NOT NULL
            REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY DEFERRED
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS "recommendation_log_id_cliente_3bee1889"
        ON "recommendation_log" ("id_cliente")
    """,
]


class Migration(migrations.Migration):
    """Crea las tablas de IA si faltan; no cambia el estado de los modelos."""

    dependencies = [
        ("innovation", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(sql=SENTENCIAS, reverse_sql=migrations.RunSQL.noop),
    ]