# Generated by Django 5.0.6 on 2026-09-21 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0002_asegurar_tablas_ia'),
        ('users_auth', '0004_fix_timestamp_timezones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAsistente',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('consulta', models.CharField(max_length=50)),
                ('filtros', models.JSONField(default=dict)),
                ('titulo', models.CharField(max_length=200)),
                ('resultado', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_auth.usuario')),
            ],
            options={
                'verbose_name': 'Reporte del asistente',
                'verbose_name_plural': 'Reportes del asistente',
                'db_table': 'reporte_asistente',
            },
        ),
    ]
