# Generated by Django 5.0.6 on 2026-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sucursal_latitud_sucursal_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='dias_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
