# Generated by Django 5.0.6 on 2026-09-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('configuracion', models.JSONField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='users_auth.usuario')),
            ],
            options={
                'verbose_name': 'Configuración Dashboard',
                'verbose_name_plural': 'Configuraciones Dashboard',
                'db_table': 'dashboard_config',
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('archivo', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_auth.usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'report_snapshot',
            },
        ),
    ]
