# Generated by Django 5.0.6 on 2026-09-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users_auth', '0004_fix_timestamp_timezones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ABANDONADO', 'Abandonado'), ('CONVERTIDO', 'Convertido')], default='ACTIVO', max_length=20)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='users_auth.cliente')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='sales.cart')),
                ('id_variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='catalog.productovariante')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='users_auth.cliente')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.sucursal')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('id_variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='catalog.productovariante')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='PosSale',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('QR', 'QR')], max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.RESTRICT, to='catalog.sucursal')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='users_auth.usuario')),
            ],
            options={
                'verbose_name': 'Venta POS',
                'verbose_name_plural': 'Ventas POS',
                'db_table': 'pos_sale',
            },
        ),
    ]
