# Generated by Django 5.0.6 on 2026-09-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta'), ('QR', 'QR')], default='TARJETA', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
