# Generated by Django 5.0.6 on 2026-09-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0002_order_metodo_pago_order_referencia_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSaleItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, to='catalog.productovariante')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.possale')),
            ],
            options={
                'verbose_name': 'Item de Venta POS',
                'verbose_name_plural': 'Items de Venta POS',
                'db_table': 'pos_sale_item',
            },
        ),
    ]
