# Generated by Django 5.0.6 on 2026-09-19 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_possaleitem'),
        ('users_auth', '0004_fix_timestamp_timezones'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_entrega',
            field=models.CharField(choices=[('RETIRO', 'Retiro en sucursal'), ('DELIVERY', 'Delivery a domicilio')], default='RETIRO', max_length=20),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=250)),
                ('referencia', models.CharField(blank=True, max_length=250, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En preparación'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_en_camino', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('id_orden', models.OneToOneField(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.order')),
                ('id_repartidor', models.ForeignKey(blank=True, db_column='id_repartidor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_asignadas', to='users_auth.usuario')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'delivery',
            },
        ),
    ]
