# Generated by Django 5.0.6 on 2026-09-24 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_fittingreservationitem_estado'),
        ('sales', '0004_order_costo_envio_order_tipo_entrega_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='id_reserva_item',
            field=models.ForeignKey(blank=True, db_column='id_reserva_item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item', to='reservations.fittingreservationitem', unique=True),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='id_reserva_item',
            field=models.ForeignKey(blank=True, db_column='id_reserva_item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale_item', to='reservations.fittingreservationitem', unique=True),
        ),
    ]
