# Generated by Django 5.0.6 on 2026-09-24 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_cartitem_id_reserva_item_possaleitem_id_reserva_item'),
        ('users_auth', '0004_fix_timestamp_timezones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada')], default='COMPLETADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='users_auth.cliente')),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='sales.order')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(choices=[('TALLA_INCORRECTA', 'Talla incorrecta'), ('COLOR_INCORRECTO', 'Color incorrecto'), ('PRODUCTO_DANADO', 'Producto dañado/defectuoso'), ('OTRO', 'Otro')], max_length=30)),
                ('id_devolucion', models.ForeignKey(db_column='id_devolucion', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.devolucion')),
                ('id_orden_item', models.ForeignKey(db_column='id_orden_item', on_delete=django.db.models.deletion.CASCADE, to='sales.orderitem')),
            ],
            options={
                'verbose_name': 'Item de Devolución',
                'verbose_name_plural': 'Items de Devolución',
                'db_table': 'devolucion_item',
            },
        ),
    ]
